#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Aura Designer - Replica Generator
=================================
Генерирует HTML в режиме source-accurate replication на базе
`AURA_SOURCE_MAP.json` и `AURADESIGN.md`.
"""

import argparse
import html
import json
import os
import re
import sys


if sys.stdout.encoding != "utf-8":
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass


def read_text(path):
    with open(path, "r", encoding="utf-8") as file:
        return file.read()


def read_json(path):
    with open(path, "r", encoding="utf-8") as file:
        return json.load(file)


def extract_colors(contract):
    colors = []
    for color in re.findall(r"#[0-9a-fA-F]{6}", contract):
        value = color.lower()
        if value not in colors:
            colors.append(value)
    fallback = ["#111827", "#ffffff", "#6366f1", "#e5e7eb"]
    return (colors + fallback)[:8]


def extract_font(contract):
    match = re.search(r'fontFamily:\s*["\']?([^"\']+)["\']?', contract)
    return match.group(1).strip() if match else "Inter"


def first(items, default=None):
    return items[0] if items else default


def build_replica_html(source_map, contract, asset_url=""):
    source = source_map.get("source", {})
    composition = source.get("composition", {})
    hero = composition.get("hero", {})
    colors = extract_colors(contract)
    font = extract_font(contract)

    title = source.get("title") or "Aura Replica"
    description = source.get("description") or "Source-accurate replica generated by Aura Designer."
    headings = source.get("headings", [])
    buttons = source.get("buttons", [])
    images = source.get("images", [])
    components = source.get("components", [])

    h1 = hero.get("headline") or (first(headings, {}) or {}).get("text") or title
    primary_image = asset_url or ((hero.get("primaryImage") or first(images, {}) or {}).get("src") if (hero.get("primaryImage") or images) else "")
    primary_cta = first(buttons, "Начать")
    secondary_cta = buttons[1] if len(buttons) > 1 else "Подробнее"

    bg = colors[1] if len(colors) > 1 else "#ffffff"
    text = "#0f172a" if bg.lower() in {"#ffffff", "#f8fafc", "#f1f5f9"} else "#ffffff"
    primary = colors[0]
    secondary = colors[2] if len(colors) > 2 else "#6366f1"
    surface = colors[3] if len(colors) > 3 else "#f3f4f6"

    image_position = hero.get("imagePosition", "center")
    title_layer_note = hero.get("headlineLayer", "normal")
    is_layered = title_layer_note in {"behind-image", "requires-manual-layer-check"} or hero.get("mustPreserveLayering")

    component_cards = []
    for component in components[:6]:
        component_cards.append(f"""
          <article class="replica-card">
            <span>{html.escape(component.get("type", "component"))}</span>
            <small>{html.escape(component.get("confidence", "detected"))}</small>
          </article>""")

    if not component_cards:
        for heading in headings[1:5]:
            component_cards.append(f"""
          <article class="replica-card">
            <span>{html.escape(heading.get("text", "Section"))}</span>
            <small>{html.escape(heading.get("tag", "h2"))}</small>
          </article>""")

    image_html = ""
    if primary_image:
        image_html = f"""<div class="hero-asset hero-asset-{html.escape(image_position)}">
          <img src="{html.escape(primary_image)}" alt="{html.escape((hero.get('primaryImage') or {}).get('alt', title))}">
        </div>"""

    return f"""<!doctype html>
<html lang="ru">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{html.escape(title)} — Aura Replica</title>
  <style>
    :root {{
      --bg: {bg};
      --text: {text};
      --primary: {primary};
      --secondary: {secondary};
      --surface: {surface};
      --line: #0f172a;
      --font-main: "{font}", system-ui, sans-serif;
    }}
    * {{ box-sizing: border-box; }}
    body {{
      margin: 0;
      background: var(--bg);
      color: var(--text);
      font-family: var(--font-main);
    }}
    a {{ color: inherit; }}
    .page {{
      min-height: 100vh;
      overflow-x: hidden;
      background-image: linear-gradient(rgba(15,23,42,.06) 1px, transparent 1px), linear-gradient(90deg, rgba(15,23,42,.06) 1px, transparent 1px);
      background-size: 40px 40px;
    }}
    .nav {{
      min-height: 76px;
      display: flex;
      align-items: center;
      justify-content: space-between;
      padding: 18px clamp(20px, 5vw, 72px);
      border-bottom: 2px solid color-mix(in srgb, var(--line), transparent 72%);
      backdrop-filter: blur(16px);
      position: sticky;
      top: 0;
      background: color-mix(in srgb, var(--bg), transparent 8%);
      z-index: 20;
    }}
    .brand {{ font-weight: 900; letter-spacing: -.04em; }}
    .nav small {{ opacity: .68; }}
    .hero {{
      position: relative;
      min-height: calc(100vh - 76px);
      display: grid;
      place-items: center;
      padding: clamp(48px, 8vw, 120px) clamp(20px, 5vw, 72px);
      isolation: isolate;
    }}
    .hero-title {{
      position: {'absolute' if is_layered else 'relative'};
      z-index: {'1' if is_layered else '3'};
      inset: {'14% 4% auto 4%' if is_layered else 'auto'};
      margin: 0;
      font-size: clamp(56px, 14vw, 210px);
      line-height: .82;
      letter-spacing: -.08em;
      text-align: center;
      text-transform: uppercase;
      color: color-mix(in srgb, var(--text), transparent {18 if is_layered else 0}%);
      pointer-events: none;
    }}
    .hero-asset {{
      position: relative;
      z-index: 4;
      width: min(58vw, 560px);
      min-width: 280px;
      aspect-ratio: 1 / 1;
      display: grid;
      place-items: center;
      margin-inline: auto;
      filter: drop-shadow(18px 18px 0 rgba(15,23,42,.20));
    }}
    .hero-asset img {{
      max-width: 100%;
      max-height: 100%;
      object-fit: contain;
    }}
    .hero-copy {{
      position: relative;
      z-index: 5;
      width: min(760px, 100%);
      margin-top: clamp(280px, 34vw, 520px);
      text-align: center;
      display: grid;
      gap: 22px;
      justify-items: center;
    }}
    .hero-copy p {{
      max-width: 720px;
      margin: 0;
      font-size: clamp(17px, 2vw, 22px);
      line-height: 1.45;
    }}
    .actions {{ display: flex; flex-wrap: wrap; gap: 14px; justify-content: center; }}
    .btn {{
      min-height: 48px;
      padding: 13px 22px;
      border: 2px solid var(--line);
      background: var(--primary);
      color: #fff;
      border-radius: 999px;
      font-weight: 800;
      text-decoration: none;
      box-shadow: 5px 5px 0 var(--line);
    }}
    .btn.secondary {{ background: var(--surface); color: var(--line); }}
    .section {{
      padding: clamp(56px, 8vw, 110px) clamp(20px, 5vw, 72px);
      border-top: 2px solid color-mix(in srgb, var(--line), transparent 76%);
    }}
    .section h2 {{ font-size: clamp(34px, 7vw, 96px); line-height: .9; letter-spacing: -.06em; margin: 0 0 30px; }}
    .grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(210px, 1fr)); gap: 22px; }}
    .replica-card {{
      min-height: 150px;
      padding: 22px;
      border: 2px solid var(--line);
      border-radius: 24px;
      background: color-mix(in srgb, var(--surface), white 45%);
      box-shadow: 7px 7px 0 var(--line);
      display: flex;
      flex-direction: column;
      justify-content: space-between;
      color: var(--line);
    }}
    .replica-card span {{ font-weight: 900; font-size: 20px; }}
    .replica-card small {{ opacity: .72; }}
    .qa-note {{
      font: 12px/1.5 ui-monospace, SFMono-Regular, Consolas, monospace;
      opacity: .68;
      max-width: 900px;
      margin-top: 32px;
    }}
    @media (max-width: 720px) {{
      .hero {{ min-height: auto; display: block; }}
      .hero-title {{ position: relative; inset: auto; font-size: clamp(54px, 22vw, 110px); margin-bottom: -24px; }}
      .hero-copy {{ margin-top: 24px; }}
      .hero-asset {{ width: min(86vw, 420px); }}
      .nav small {{ display: none; }}
    }}
  </style>
</head>
<body>
  <main class="page">
    <header class="nav">
      <div class="brand">{html.escape(title)}</div>
      <small>copy-in-copy source replica</small>
    </header>

    <section class="hero">
      <h1 class="hero-title">{html.escape(h1)}</h1>
      {image_html}
      <div class="hero-copy">
        <p>{html.escape(description)}</p>
        <div class="actions">
          <a class="btn" href="#content">{html.escape(primary_cta)}</a>
          <a class="btn secondary" href="#source-map">{html.escape(secondary_cta)}</a>
        </div>
      </div>
    </section>

    <section class="section" id="content">
      <h2>Карта компонентов</h2>
      <div class="grid">
        {''.join(component_cards)}
      </div>
      <p class="qa-note" id="source-map">
        Реплика построена из AURA_SOURCE_MAP.json. Для pixel-perfect результата sub-agent должен дополнить JSON координатами из browser snapshot/screenshots и прогнать AURA_VISUAL_QA.md.
      </p>
    </section>
  </main>
</body>
</html>
"""


def main():
    parser = argparse.ArgumentParser(description="Aura Designer source replica generator")
    parser.add_argument("--source-map", default="AURA_SOURCE_MAP.json", help="Путь к AURA_SOURCE_MAP.json")
    parser.add_argument("--contract", default="AURADESIGN.md", help="Путь к AURADESIGN.md")
    parser.add_argument("--output", default="index.html", help="Файл HTML")
    parser.add_argument("--asset-url", default="", help="Принудительный URL hero-ассета")
    args = parser.parse_args()

    source_map = read_json(args.source_map)
    contract = read_text(args.contract)
    html_output = build_replica_html(source_map, contract, args.asset_url)

    with open(args.output, "w", encoding="utf-8") as file:
        file.write(html_output)

    print(f"[OK] Source-accurate replica сохранена: {args.output}")


if __name__ == "__main__":
    main()
